apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
spec:
  type: {{ .Values.service.type }}
  selector:
    project: roboshop
    component: frontend
    environment: dev
    purpose: load-balancer
  ports: 
  - protocol: TCP
    port: {{ .Vlaues.service.ServicePort }}
    targetPort: 80
    nodePort: 30007
